// File generated by FlutterFire CLI.
// This file will be auto-generated once you run: flutterfire configure
// For now, this is a placeholder. You'll need to run flutterfire configure
// or manually add your Firebase configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR7Tl3vJYzeStD0Kpg1Vg_jFM7-6xWHUA',
    appId: '1:564219513849:web:placeholder',
    messagingSenderId: '564219513849',
    projectId: 'sprouts-dd497',
    authDomain: 'sprouts-dd497.firebaseapp.com',
    storageBucket: 'sprouts-dd497.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR7Tl3vJYzeStD0Kpg1Vg_jFM7-6xWHUA',
    appId: '1:564219513849:android:3a7d12ce6a3512153b8b28',
    messagingSenderId: '564219513849',
    projectId: 'sprouts-dd497',
    storageBucket: 'sprouts-dd497.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdu3FCzPakS4VRlu-2OvmR8AvBEZyqi_A',
    appId: '1:564219513849:ios:4324983642bb7f373b8b28',
    messagingSenderId: '564219513849',
    projectId: 'sprouts-dd497',
    storageBucket: 'sprouts-dd497.firebasestorage.app',
    iosBundleId: 'com.sprouts.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdu3FCzPakS4VRlu-2OvmR8AvBEZyqi_A',
    appId: '1:564219513849:ios:4324983642bb7f373b8b28',
    messagingSenderId: '564219513849',
    projectId: 'sprouts-dd497',
    storageBucket: 'sprouts-dd497.firebasestorage.app',
    iosBundleId: 'com.sprouts.app',
  );
}
