begin;

create table vanimals (
	vanimal_id bigint generated by default as identity not null,
	owner text not null,
	matron_id bigint not null,
	sire_id bigint not null,
	genes text not null,
	is_featured bool default false,
	image_url text,
	name text,
	short_description text,
	population text,
	status text,
	distribution text,
	description text,
	location text,
	rarity text,
	updated_at timestamp default now(),
	created_at timestamp default now(),
	constraint vanimal_pkey primary key (vanimal_id)
);

commit;
