require("dotenv").config();
const { createPrefixedId } = require("./utils");
const cpuCount = require("os").cpus().length;

const {
  NODE_ENV,
  WORKER_NUMBER,
  SHOULD_CLUSTER,
  CLUSTER_MAX_INSTANCES,
  JWT_SIGNING_SECRET,
  CLIENT_MINIMUM_VERSION,

  ADMIN_SECRET,

  DANGEROUSLY_ENABLE_TESTING_TOOLS,
  COINMARKETCAP_API_KEY,
  PORT,
  API_PORT,
  API_HOST,
  API_CORS,
  API_ACCESS_TOKEN,

  npm_package_version,

  DB_CONNECTION_URI,
  DB_MAX_POOL_SIZE,
  DB_MIN_POOL_SIZE,
  DB_NAME,
  DB_VERBOSE,

  AWS_BUCKET_NAME,
  AWS_ACCESS_KEY,
  AWS_SECRET_KEY,

  STRIPE_PUBLISHABLE_KEY,
  STRIPE_SECRET_KEY,

  CKB_PAYMENT_MINUTES_EXPIRE,
  CKB_PAYMENT_MINUTES_SPAN,
  CKB_QUOTE_LIFE,
  CKB_INDEXER_URL,
  CKB_NODE_URL,
  CKB_PREFIX,

  GOOGLE_OAUTH_SECRET
} = process.env;

if (!NODE_ENV) {
  // eslint-disable-next-line no-console
  console.warn("NODE_ENV not set, defaulting to development");
  process.env.NODE_ENV = "development";
}

module.exports = {
  WORKER_NUMBER: WORKER_NUMBER || 0,
  WORKER_NAME: createPrefixedId("wrk"),
  SHOULD_CLUSTER,
  JWT_SIGNING_SECRET,
  CLIENT_MINIMUM_VERSION,

  ADMIN_SECRET,

  DANGEROUSLY_ENABLE_TESTING_TOOLS: DANGEROUSLY_ENABLE_TESTING_TOOLS,

  CLUSTER_MAX_INSTANCES: Number(CLUSTER_MAX_INSTANCES) || cpuCount,
  NODE_ENV,
  VERSION: npm_package_version,
  IS_TESTING: NODE_ENV === "testing",
  IS_DEVELOPMENT: NODE_ENV === "development",
  IS_PRODUCTION: NODE_ENV === "production",
  COINMARKETCAP: {
    API_KEY: COINMARKETCAP_API_KEY
  },
  AWS: {
    BUCKET_NAME: AWS_BUCKET_NAME,
    ACCESS_KEY: AWS_ACCESS_KEY,
    SECRET_KEY: AWS_SECRET_KEY
  },
  API: {
    CORS: API_CORS,
    ACCESS_TOKEN: API_ACCESS_TOKEN,
    PORT: PORT || API_PORT || 3000,
    HOST: API_HOST,
  },
  DB: {
    NAME: DB_NAME,
    VERBOSE: DB_VERBOSE,
    CONNECTION_URI: DB_CONNECTION_URI,
    MIN_POOL_SIZE: DB_MIN_POOL_SIZE || 1,
    MAX_POOL_SIZE: DB_MAX_POOL_SIZE || 20
  },
  STRIPE: {
    PUBLISHABLE_KEY: STRIPE_PUBLISHABLE_KEY,
    SECRET_KEY: STRIPE_SECRET_KEY,
  },
  CKB: {
    PAYMENT_MINUTES_EXPIRE: CKB_PAYMENT_MINUTES_EXPIRE || 30,
    PAYMENT_MINUTES_SPAN: CKB_PAYMENT_MINUTES_SPAN || 15,
    QUOTE_LIFE: CKB_QUOTE_LIFE || 120,
    PREFIX: CKB_PREFIX || "ckt",
    INDEXER_URL: CKB_INDEXER_URL || "http://3.235.223.161:18116",
    NODE_URL: CKB_NODE_URL || "http://3.235.223.161:18114",
    // ISSUER_TYPE_SCRIPT: CKB_ISSUER_TYPE_CELL.ISSUER_TYPE_SCRIPT,
  },
  GOOGLE: {
    OAUTH_SECRET: GOOGLE_OAUTH_SECRET
  }
};
