module.exports = {
  STATS_TYPES: {
    INSTAGRAM_FOLLOWERS: "INSTAGRAM_FOLLOWERS",
    SPOTIFY_FOLLOWERS: "SPOTIFY_FOLLOWERS",
    TWITTER_FOLLOWERS: "TWITTER_FOLLOWERS",
    TWITTER_TWETTS: "TWITTER_TWETTS",
  },
  ASSET_TYPES: {
    IMAGE: "IMAGE",
    VIDEO: "VIDEO",
    MODEL: "MODEL",
    INSTAGRAM_USERNAME: "INSTAGRAM_USERNAME",
    TWITTER_USERNAME: "TWITTER_USERNAME",
    TWITTER_USERID: "TWITTER_USERID",
    SPOTIFY_USERID: "SPOTIFY_USERID",
  },
  MINTED_STATUS: "MINTED",
  CKB_STATUS: {
    PENDING_CONFIRMATION: "PENDING_CONFIRMATION",
    PENDING_ACTION: "PENDING_ACTION",
    CANCELLED: "CANCELLED",
    SUCCEEDED: "SUCCEEDED",
    EXPIRED: "EXPIRED",
  },
  STRIPE_STATUS: {
    REQUIRES_PAYMENT_METHOD: "REQUIRES_PAYMENT_METHOD",
    REQUIRES_SOURCE_ACTION: "REQUIRES_ACTION",
    REQUIRES_SOURCE: "REQUIRES_SOURCE",
    REQUIRES_ACTION: "REQUIRES_ACTION",
    SUCCEEDED: "SUCCEEDED",
  },
  PROTOTYPE_CATEGORY: {
    ACTORS: "ACTORS",
    MUSICIAN: "MUSICIAN",
    POLITICIAN: "POLITICIAN",
    ENTREPRENEUR: "ENTREPRENEUR",
    ATHLETES: "ATHLETES",
    OTHER: "OTHER",
  },
  ITEM_FILTERS: {
    BEST_SELLERS: "BEST_SELLERS",
    NEW_RELEASES: "NEW_RELEASES",
    TRENDING: "TRENDING",
    POPULAR: "POPULAR",
  },
  ITEM_TYPE: {
    PROTOTYPE: "PROTOTYPE",
    PACK: "PACK",
  },
  GAME: {
    MAX_INSTANCES_IN_DECK: 3,
    MAX_N00_POINTS: 5,
  }
};
