begin;

create table facebook_accounts (
	facebook_account_id bigint generated by default as identity not null,
	access_token text not null,
	external_facebook_account_id text not null,
	updated_at timestamp default now(),
	created_at timestamp default now(),
	constraint facebook_account_pkey primary key (facebook_account_id)
);

commit;
