begin;

create table vanimals (
	vanimal_id bigint generated by default as identity not null,
	is_gestating bool not null,
	is_ready bool not null,
	cooldown_index bigint not null,
	next_action_at bigint not null,
	siring_with_id bigint not null,
	birth_time bigint not null,
	matron_id bigint not null,
	sire_id bigint not null,
	generation bigint not null,
	genes text not null,
	updated_at timestamp default now(),
	created_at timestamp default now(),
	constraint vanimal_pkey primary key (vanimal_id)
);

commit;
